# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 22:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='DailyLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_id', models.UUIDField(default=uuid.uuid4)),
                ('label', models.CharField(max_length=64)),
                ('frequency', models.CharField(choices=[('1', 'Weekly'), ('2', 'Bi-Weekly'), ('3', 'Monthly'), ('4', 'Bi-Monthly'), ('5', 'Quarterly'), ('6', 'Semi Annually'), ('7', 'Annually')], default='3', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='ScheduledTransaction',
            fields=[
                ('transaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='money.Transaction')),
                ('weekly', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
            ],
            bases=('money.transaction',),
        ),
        migrations.AddField(
            model_name='transaction',
            name='ledger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='money.DailyLedger'),
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('scheduledtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='money.ScheduledTransaction')),
            ],
            bases=('money.scheduledtransaction',),
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('scheduledtransaction_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='money.ScheduledTransaction')),
            ],
            bases=('money.scheduledtransaction',),
        ),
    ]
