# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 01:43
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_id', models.UUIDField(default=uuid.uuid4)),
                ('type', models.CharField(choices=[('1', 'Reoccurring'), ('2', 'Purchase'), ('3', 'Bill')], max_length=1)),
                ('frequency', models.CharField(choices=[(b'7', b'ANNUALLY'), (b'4', b'BIMONTHLY'), (b'2', b'BIWEEKLY'), (b'3', b'MONTHLY'), (b'5', b'QUARTERLY'), (b'6', b'SEMIANNUALLY'), (b'1', b'WEEKLY')], default='3', max_length=1)),
                ('label', models.CharField(max_length=64)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('weekly', models.DecimalField(decimal_places=2, max_digits=5)),
                ('yearly', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
