# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-11 00:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLedger',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4)),
                ('type', models.CharField(choices=[('1', 'Purchase'), ('2', 'Bill'), ('3', 'Withdraw'), ('4', 'Deposit')], default='1', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('ledger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='money.DailyLedger')),
            ],
        ),
    ]
