# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-07 02:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_auto_20170807_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='monthly',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
