# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 21:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0002_dailyledger_transaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='ledger',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='money.DailyLedger'),
        ),
    ]
