# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-25 23:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_auto_20170825_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='automatic',
            field=models.BooleanField(default=False),
        ),
    ]
