# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-08 01:22
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0003_expense_monthly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=64)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=12)),
            ],
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('natural_id', models.UUIDField(default=uuid.uuid4)),
                ('label', models.CharField(max_length=64)),
                ('frequency', models.CharField(choices=[('1', 'Weekly'), ('2', 'Bi-Weekly'), ('3', 'Monthly'), ('4', 'Bi-Monthly'), ('5', 'Quarterly'), ('6', 'Semi Annually'), ('7', 'Annually')], default='3', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7)),
                ('weekly', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('monthly', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('yearly', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('daily', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('type', models.CharField(choices=[('1', 'Reoccurring'), ('2', 'Gift')], max_length=1)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='expense',
            name='frequency',
            field=models.CharField(choices=[('1', 'Weekly'), ('2', 'Bi-Weekly'), ('3', 'Monthly'), ('4', 'Bi-Monthly'), ('5', 'Quarterly'), ('6', 'Semi Annually'), ('7', 'Annually')], default='3', max_length=1),
        ),
    ]
