# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-13 18:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0005_auto_20170826_0536'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailyledger',
            name='ending_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailyledger',
            name='starting_balance',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
