# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-14 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0006_auto_20170913_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('1', 'Canada'), ('2', 'United States')], default='1', max_length=1),
        ),
    ]
