# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 22:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('money', '0007_transaction_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyledger',
            name='ending_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='dailyledger',
            name='starting_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='currency',
            field=models.CharField(choices=[('1', 'Canadian (CAD)'), ('2', 'American (USD)')], default='1', max_length=1),
        ),
    ]
